apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-stqi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-stqi@sha256:45324cc7cfa08f9a2ccc26482b7bab74346a41d53a55270c5dbf678e1519ff6e
        name: my-nodejs
        resources: {}
status: {}
